#!/usr/bin/env python3

import re
import subprocess

def get_pushing_branch_name() -> str:
    # stdin: <local_ref> <local_sha1> <remote_ref> <remote_sha1>
    # sample:
    #     local_ref   = refs/heads/master
    #     local_sha1  = 68a07ee4f6af8271dc40caae6cc23f283122ed11
    #     remote_ref  = refs/heads/master
    #     remote_sha1 = efd4d512f34b11e3cf5c12433bbedd4b1532716f

    branch_name = ''

    try: 

        local_ref, local_sha1, remote_ref, remote_sha1 = input().split()
        branch_name = remote_ref.replace('refs/heads/', '')

    except EOFError as e:
        prefix = 'warning: '
        spaces = ' ' * len(prefix)
        print(prefix + 'Read the EOF!')
        print(spaces + 'Maybe you have nothing to push.')
        exit(0)

    return branch_name


def check_pushing():

    patterns = ['main']

    branch = get_pushing_branch_name()
    is_matched = False

    for pattern in patterns:
        if re.match(pattern, branch) != None:
            is_matched = True

    if is_matched:
        prefix = 'warning: '
        print(prefix + 'Push to remote ' + branch + ', continue? [y/N]', end=' ', flush=True)

        res = subprocess.run('exec < /dev/tty; read ANSWER; echo $ANSWER', shell=True, capture_output=True, text=True)
        answer = res.stdout

        if answer == '\n' or answer[0] == 'n' or answer[0] == 'N':
            print('Push cancelled.')
            exit(1)
        else:
            print('OK. Push start.')


def main():
    check_pushing()

main()
