name: include guard check

on:
  pull_request:

jobs:
  checking-include-guard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: checking
      run: |
        for file in $(git diff ${{ github.event.before }}..${{ github.event.after }} --name-only -- "*.hpp") ; do
          echo file
          head -n 1 file | xargs echo | sed "s/ //g" | xargs test \#pragmaonce =
          if [ $? != 0 ]; then
            echo 'Failed'
            exit 1
          fi
        done
        echo 'Succeed!'
        exit 0
    - name: Dump file
      run: echo $(git diff ${{ github.event.before }}..${{ github.event.after }} --name-only)