name: c++ compile

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v17.3

    - name: Install g++
      run: |
        sudo apt install g++

    - name: Print g++ version
      run: |
        g++ --version

    # 拡張子が .cpp or .hpp のもののみ
    - name: Compile
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if [ "${file##*.}" = ".cpp" ] || [ "${file##*.}" = ".hpp" ]; then
            g++ $file
          fi
        done
