name: clang-format

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.LINTER_TOKEN }}

    - name: Install clang-format
      run: |
        sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
        sudo apt update
        sudo apt install clang-format

    - name: Set git config
      run: |
        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "matumoto1234"

    - name: Run format
      run: |
        clang-format -i -style=file ./*
        git add .
        set +e
        git commit -m 'clang-format by GitHub Actions'

    - name: Push
      run: |
        git push origin ${{ github.ref }}