name: clang-format

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.LINTER_TOKEN }}
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: '.'
        extensions: 'cpp,hpp'
        clangFormatVersion: 12
        style: file
        inplace: True
    - name: push
      run: |
        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "matumoto1234"
        git add .
        git commit -m "clang-format by GitHub Actions"
        git push origin