name: verify

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Cache .verify-helper
      id: verify-helper-cache-id
      uses: actions/cache@v3
      with:
        path: ~/.verify-helper
        key: ${{ runner.os }}-verify-${{ hashFiles('**/timestamps.remote.json') }}

    - name: Pull gh-pages branch
      run: |
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name $GITHUB_ACTOR
        git switch -c 'gh-pages'
        git fetch
        git merge --allow-unrelated-histories origin/gh-pages
        git switch -

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
      run: oj-verify all
